"""add nullable owner id to books

Revision ID: 368175169c88
Revises: 1bfd1f65450a
Create Date: 2026-08-11 19:10:31.091236

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "368175169c88"
down_revision: Union[str, Sequence[str], None] = "1bfd1f65450a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("books", schema=None) as batch_op:
        batch_op.add_column(sa.Column("owner_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_books_owner_id_users", "users", ["owner_id"], ["user_id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("books", schema=None) as batch_op:
        batch_op.drop_constraint("fk_books_owner_id_users", type_="foreignkey")
        batch_op.drop_column("owner_id")

    # ### end Alembic commands ###
