"""make isbn not null

Revision ID: de1c8b4db0bb
Revises: 58bb8935c9ad
Create Date: 2026-07-26 22:35:51.322636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de1c8b4db0bb'
down_revision: Union[str, Sequence[str], None] = '58bb8935c9ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
