"""add publishers and book foreign key

Revision ID: f481e0cbd250
Revises: 56113ba8ee03
Create Date: 2026-07-27 14:47:46.477597

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f481e0cbd250"
down_revision: Union[str, Sequence[str], None] = "56113ba8ee03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "publishers",
        sa.Column("publisher_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("publisher_id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("books", schema=None) as batch_op:
        batch_op.add_column(sa.Column("publisher_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_books_publisher_id_publishers",
            "publishers",
            ["publisher_id"],
            ["publisher_id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("books", schema=None) as batch_op:
        batch_op.drop_constraint("fk_books_publisher_id_publishers", type_="foreignkey")
        batch_op.drop_column("publisher_id")

    op.drop_table("publishers")
    # ### end Alembic commands ###
